
import javax.swing.JOptionPane;

/**
     * Class Name: HockettjFrame
     * Class Author: Tyler Hockett
     * **************************
     * Purpose of the Class
     * Collect ten numbers to be calculated
     * into an average and standard dev.
     * **************************
     * Date: 9/5/2017 USA
     * **************************
     * Date Changed:9/6/2017 USA
     * **************************
     * Look At This!
     * Its all pretty cool. 
     * 
     * **************************
     */
public class HockettjFrame extends javax.swing.JFrame {
    doMath m = new doMath();
    String response;
    int count=1;
    boolean printed = false;
    /**
     * Creates new form HockettjFrame
     */
    public HockettjFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumbers = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblAvg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSD = new javax.swing.JLabel();
        lblNumbers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter 10 more numbers:");

        txtNumbers.setName("txtNumbers"); // NOI18N
        jScrollPane1.setViewportView(txtNumbers);
        txtNumbers.getAccessibleContext().setAccessibleName("txtNumbers");

        jLabel2.setText("Average:");

        btnAdd.setText("ADD");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblAvg.setName("lblAvg"); // NOI18N

        jLabel4.setText("Standard Deviation:");

        lblSD.setName("lblSD"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblAvg)
                    .addComponent(jLabel4)
                    .addComponent(lblSD)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvg)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(lblSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblNumbers)
                .addGap(25, 25, 25))
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblNumbers");
        btnAdd.getAccessibleContext().setAccessibleName("btnAdd");
        btnAdd.getAccessibleContext().setAccessibleDescription("");
        lblAvg.getAccessibleContext().setAccessibleName("lblAvg");
        lblSD.getAccessibleContext().setAccessibleName("lblSD");

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Method Name: btnAddActionPerformed
     * Method Author: Tyler Hockett
     * **************************
     * when the button is pressed it
     * will collect the input and pass it to
     * the doMath object/class to validate and 
     * store for the math functions.
     * At 11 the button name will change
     * and the math will be calculated
     * and stored in the respective 
     * labels.
     * **************************
     * Date: 9/6/2017 USA
     * **************************
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(count<=10)
        {
            response=txtNumbers.getText();
            m.addThis(response);
            lblNumbers.setText(m.writeThis());
            count++;
            txtNumbers.setText("");
            txtNumbers.grabFocus();
            if(count==11)
            {
                m.findAnswer();
                lblSD.setText(m.writeSD());
                lblAvg.setText(m.writeAvg());
                printed = true;
                btnAdd.setText("Reset");
                lblNumbers.setText(" ");
            }
        }
        else
        {
            if(printed == true)
            {
               btnAdd.setText("Add"); 
               count = 1;
               lblSD.setText("");
               lblNumbers.setText("");
               lblAvg.setText("");
               m = new doMath();
               printed = false;
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HockettjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HockettjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HockettjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HockettjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HockettjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvg;
    private javax.swing.JLabel lblNumbers;
    private javax.swing.JLabel lblSD;
    private javax.swing.JTextPane txtNumbers;
    // End of variables declaration//GEN-END:variables
}
